In [43]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import re
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
from sklearn.metrics import accuracy_score
import nltk
nltk.download('stopwords')
import math
from sklearn.model_selection import train_test_split

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [44]:
data=pd.read_csv('/content/spam.csv',encoding="ISO-8859-1")
data=pd.DataFrame(data)
data.head(5)

v1                                                 v2 Unnamed: 2  \
0   ham  Go until jurong point, crazy.. Available only ...        NaN   
1   ham                      Ok lar... Joking wif u oni...        NaN   
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3   ham  U dun say so early hor... U c already then say...        NaN   
4   ham  Nah I don't think he goes to usf, he lives aro...        NaN   

  Unnamed: 3 Unnamed: 4  
0        NaN        NaN  
1        NaN        NaN  
2        NaN        NaN  
3        NaN        NaN  
4        NaN        NaN

In [45]:
data=data[['v1','v2']].copy()
data.head()

v1                                                 v2
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [46]:
data.rename(columns={'v1':'label','v2':'text'},inplace=True)
data.label[data.label == 'ham'] = 0
data.label[data.label== 'spam'] = 1

In [47]:
data.head()

label                                               text
0     0  Go until jurong point, crazy.. Available only ...
1     0                      Ok lar... Joking wif u oni...
2     1  Free entry in 2 a wkly comp to win FA Cup fina...
3     0  U dun say so early hor... U c already then say...
4     0  Nah I don't think he goes to usf, he lives aro...

In [48]:
port_stem=PorterStemmer()
def stemming(content):
    stemmed_content = re.sub('[^a-zA-Z]',' ',content)
    stemmed_content = stemmed_content.lower()
    stemmed_content = stemmed_content.split()
    stemmed_content = [port_stem.stem(word) for word in stemmed_content if not word in stopwords.words('english')]
    stemmed_content = ' '.join(stemmed_content)
    return stemmed_content

In [49]:
data['text'] = data['text'].apply(stemming)

In [50]:
x=data.drop(columns="label")
y=data['label']


In [51]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,stratify=y,random_state=5)

In [52]:
result = pd.concat([x_train, y_train], axis=1, join='inner').copy()


In [53]:
ham_array=result.groupby(data.label).get_group(0)
spam_array=result.groupby(data.label).get_group(1)
spam={}
ham={}



In [54]:

ham_size=ham_array.size
spam_size=spam_array.size

spam_array=spam_array.drop(columns='label',axis=1)
spam_array_values=spam_array['text'].values
# print(spam_array_values)

spam_words=0
for sent in spam_array_values:
  words=sent.split()
  # spam_words+=len(words)
  for word in words:
    if word in spam:
      spam[word]+=1
    else:
      spam[word]=2

spam_words=sum(spam.values())
print(spam_words)
print(spam)




10943
{'b': 23, 'floppi': 2, 'snappi': 2, 'happi': 2, 'gay': 7, 'chat': 38, 'servic': 57, 'photo': 3, 'upload': 3, 'call': 328, 'p': 147, 'min': 75, 'stop': 97, 'text': 122, 'freemsg': 10, 'hey': 6, 'darl': 2, 'week': 56, 'word': 20, 'back': 18, 'like': 11, 'fun': 9, 'still': 7, 'tb': 2, 'ok': 6, 'xxx': 12, 'std': 12, 'chg': 3, 'send': 56, 'rcv': 3, 'today': 32, 'voda': 5, 'number': 35, 'end': 23, 'select': 29, 'receiv': 33, 'award': 57, 'match': 12, 'pleas': 44, 'quot': 5, 'claim': 98, 'code': 26, 'standard': 5, 'rate': 33, 'app': 4, 'messag': 39, 'free': 187, 'welcom': 8, 'new': 56, 'improv': 2, 'sex': 9, 'dog': 8, 'club': 20, 'unsubscrib': 17, 'repli': 83, 'msg': 47, 'want': 23, 'get': 70, 'laid': 3, 'tonight': 4, 'real': 12, 'locat': 3, 'sent': 7, 'direct': 9, 'ur': 120, 'mob': 22, 'join': 16, 'uk': 59, 'largest': 3, 'network': 21, 'txting': 9, 'moan': 2, 'nyt': 4, 'ec': 4, 'orang': 22, 'custom': 38, 'may': 6, 'camera': 32, 'phone': 49, 'upgrad': 5, 'loyalti': 6, 'offer': 38, 'thma

In [55]:
ham_array=ham_array.drop(columns='label',axis=1)
ham_array_values=ham_array['text'].values

ham_words=0
for sent in ham_array_values:
  words=sent.split()
  # spam_words+=len(words)
  for word in words:
    if word in ham:
      ham[word]+=1
    else:
      ham[word]=2

ham_words=sum(ham.values())
print(ham_words)
print(ham)

35567
{'got': 202, 'tallent': 2, 'wast': 9, 'ye': 69, 'outsid': 11, 'like': 186, 'hour': 37, 'call': 237, 'whole': 13, 'famili': 21, 'wake': 25, 'caus': 20, 'start': 45, 'two': 25, 'letter': 8, 'copi': 11, 'co': 61, 'one': 135, 'messag': 70, 'speak': 21, 'soon': 48, 'oh': 90, 'thank': 79, 'lot': 41, 'alreadi': 80, 'bought': 6, 'egg': 8, 'see': 129, 'requir': 5, 'pleas': 63, 'left': 29, 'orchard': 7, 'cool': 32, 'time': 193, 'think': 123, 'get': 312, 'know': 197, 'cheesi': 2, 'song': 11, 'frosti': 2, 'snowman': 3, 'good': 190, 'morn': 70, 'dear': 82, 'great': 97, 'amp': 77, 'success': 8, 'day': 197, 'hi': 92, 'spoke': 6, 'maneesha': 3, 'v': 42, 'satisfi': 3, 'experi': 7, 'repli': 43, 'toll': 3, 'free': 51, 'head': 20, 'straight': 4, 'sorri': 127, 'later': 109, 'lt': 268, 'gt': 269, 'min': 35, 'erm': 4, 'thought': 43, 'contract': 3, 'ran': 4, 'th': 32, 'octob': 2, 'say': 105, 'give': 86, 'friend': 71, 'money': 44, 'definit': 6, 'buy': 56, 'end': 33, 'week': 56, 'plan': 48, 'come': 233, '

In [56]:
def helper(content):
  words=stemming(content).split(' ')
  ham_prob=ham_size/(ham_size+spam_size)
  for word in words:
    if word in ham:
      ham_prob*= ((ham[word])/ham_words)
    else:
      ham_prob*=1
  spam_prob=spam_size/(ham_size+spam_size)
  for word in words:
    if word in spam:
      spam_prob*=((spam[word])/spam_words)
    else:
      spam_prob*=1

  if(ham_prob>spam_prob):
    # print("ham",0)
    return 1
  else:
    return 0

In [57]:

result['val']=result['text'].apply(helper)

In [58]:
print(result)

                                                   text label  val
3027                                   got tallent wast     0    0
4434  b floppi b snappi happi gay chat servic photo ...     1    0
5     freemsg hey darl week word back like fun still...     1    1
1806  today voda number end select receiv award matc...     1    1
3450  ye outsid like hour call whole famili wake cau...     0    0
...                                                 ...   ...  ...
3783                dear got train seat mine lower seat     0    0
336                          cool come havent wine dine     0    0
4356  hellogorg how u fone charg lst nitw wen u texd...     0    0
1620  fuck babe miss sooooo much wish sleep bed lone...     0    0
3424                                        true easier     0    0

[4457 rows x 3 columns]


In [59]:
actual=result['label'].to_numpy()
pred=result['val'].to_numpy()
print(actual)
print(pred)
crt=0
total=actual.size
for i in range(actual.size):
  if actual[i] == pred[i]:
    crt+=1
print((crt/total)*100)

[0 1 1 ... 0 0 0]
[0 0 1 ... 0 0 0]
85.90980480143594


In [64]:
result2=pd.concat([x_test, y_test], axis=1, join='inner').copy()

In [65]:
print(result2)

                                                   text label
1590  somewhr someon sure made u god decid perfect t...     0
881   see knew give break time woul lead alway want ...     0
3551                              lol u still feel sick     0
1971                           enjoy ur life good night     0
2430                                       txting drive     0
...                                                 ...   ...
2451  know complain num bettr directli go bsnl offc ...     0
5032                    realli good see day dudett miss     0
883                                         dude go sup     0
4429                       yar lor u noe u use dat rout     0
3916  eh ur laptop got stock lei say mon muz come ta...     0

[1115 rows x 2 columns]


In [66]:
result2['val']=result2['text'].apply(helper)

In [67]:
actual=result2['label'].to_numpy()
pred=result2['val'].to_numpy()
print(actual)
print(pred)
crt=0
total=actual.size
for i in range(actual.size):
  if actual[i] == pred[i]:
    crt+=1
print((crt/total)*100)

[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
80.98654708520179
